spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: giusealba644@gmail.com
    password: znfyiqkvoelazyvf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
